---
title: "Project Proposal"
author: marissa zimmer 
output: 
    github_document
---
## Introduction to problem/question ##

Within NYS many have been asking the question of, where are all the wild turkeys? 
 Some areas we have seen an increase over the years but in certain areas we have 
 noticed a decline in localized populations. By looking at different environmental variables 
 it is possible to help identify how turkeys can be impacted by environmental changes 
 associated with climate change. 


## Problem / Question ##
Does climate and habitat change negativly impact wild turkey populations within New York State?

## Example 1##
  https://www.researchgate.net/figure/MaxEnt-species-distribution-models-for-six-higher-attine-nonleaf-cutter-ant-species-in_fig2_338064443 
This study uses maxent to show species sutability of six different
higher-attine nonleaf cutter ant species. I liked this example as it shows
6 different ant species side by side with different suitabilites. 
  

## Example 2##
https://www.researchgate.net/figure/Results-of-species-distribution-modeling-SDM-employing-Maxent-algorithm-for-the_fig1_324076008

Results of species distribution modeling (SDM) using Maxent for 
the species Lagostomus maximus (left column) and Myocastor coypus (right). The 
suitability projections for current time are showed in continuous scale
(between 0 and 1). 

## Example 3 ##
https://roanoke.com/sports/outdoors/virginia-s-turkey-management-plan-finally-set/article_2a8137b8-904e-11e3-91da-0017a43b2370.html?mode=image&photo=2

I liked the graphic that they used within this article. 
Here they used spring gobbler suitability and then 
mapped where the population trends are increasing or 
decreasing. This shows that once I produce my maps and SDMs they could be useful
to different people for different reasons like how to actively manage wild
turkey populations within certain areas. 


## Proposed data sources ##
Turkey data: 
  eBird data from 1991-2021 on all wild turkey sightings withn NYS
  NYSDEC citizen survey data from 1999-2020
  NYSDEC Spring harvest gobbler report 2011-2020
  Worldclim data (max temp and precip)
  land cover change for NY from Dr. Williams data she provided
  Tree cover/ change for NY from Dr. Williams data she provided
  maxent

## Proposed methods
The first step would be to create multiple maps/graphs/tables all at the same spatial scale
of 1 km if possible. The maps would include: 
  NY shapefile 
  NY county lines within the shapefile 
  max temperature for NY from Worldclim 
  max precipitaiton for NY from worldclim
  land cover change for NY from Dr. Williams data she provided
  Tree cover/ change for NY from Dr. Williams data she provided

  
The second step would be to create a SDM. 

  create the SDM to see the suitablity score using Maxent. 
  
## Expected results ##
 I am hoping that the results will show that in areas where turkey populations have seen population
 declines there has also been increased precipitation, changing land use and tree cover.
 I would also expect to see a decrease in the species suitablitly score within these areas 
 

At the very end of this I would like to have one SDM comparing all my environmental factor
to the number of wild turkey observations and/ or a map of NYS by county showing suitability like the one
in my third example link. 
I should have at least 3 maps from my first step and at 
least one map of the number of obersavtions. The number of observations will also make a nice table. 


